openapi: 3.0.3
info:
  title: TagExtractionBusinessService
  description: Service that extracts tag from the reviews
  version: 1.0.0
servers:
  - url: https://tag-logic/api/v1
paths:
  /:
    post:
      summary: Tag extractor
      description: Extracts tag from the reviews of a sitting spot
      operationId: tagExtractor
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
        required: true
      responses:
        '200':
          description: tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Label'
        '400':
          description: Invalid input

components:
  schemas:
    Review:
      properties:
        corpus:
          type: string

    Label:
      properties:
        value:
          type: string
