openapi: 3.0.3
info:
  title: TagExtractionBusinessService
  description: Service that extracts tag from the reviews
  version: 1.0.0
servers:
  - url: http://tagextractor/api/v1
paths:
  /{Id}:
    post:
      summary: Tag extractor
      description: Extracts tag from the reviews of a sitting spot
      operationId: tagExtractor
      parameters:
        - name: Id
          in: path
          description: ID of the sitting spot
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Label'
        '400':
          description: Invalid input

components:
  schemas:
    Review:
      properties:
        corpus:
          type: string

    Label:
      properties:
        value:
          type: string
